In [1]:
from skimage.exposure import rescale_intensity
import numpy as np
import cv2

In [2]:
def convolve(image, K):
    
    (iH, iW) = image.shape[:2]
    (kH, kW) = K.shape[:2]
    
    
    pad = (kW - 1) //2
    image = cv2.copyMakeBorder(image, pad, pad, pad, pad, cv2.BORDER_REPLICATE)
    output = np.zeros((iH, iW), dtype="float")
    for y in np.arange(pad,pad+iH):
        for x in np.arange( pad, pad + iW):
            roi = image[y - pad:y + pad +1, x-pad: x+pad +1]
            
            k = (roi*K).sum()
            
            
            output[y - pad, x-pad] = k
            
            
            
    print(output)
    output = rescale_intensity(output, in_range=(0, 255))
    print(output)
    output = (output * 255).astype("uint8")
    
    return output

In [3]:
smallBlur = np.ones((7, 7), dtype="float") * (1.0 / (7 * 7))
largeBlur = np.ones((21, 21), dtype="float") * (1.0 / (21* 21))


In [4]:
sharpen = np.array(([0, -1, 0], [-1, 5, -1], [0, -1, 0]), dtype="int")

In [5]:
laplacian = np.array(([0, 1, 0],[1, -4, 1],[0, 1, 0]), dtype="int")

In [6]:
sobelX = np.array(( [-1, 0, 1], [-2, 0, 2], [-1, 0, 1]), dtype="int")

In [7]:
sobelY = np.array(( [-1, -2, -1], [0, 0, 0], [1, 2, 1]), dtype="int")

In [8]:
emboss = np.array(( [-2, -1, 0], [-1, 1, 1], [0, 1, 2]), dtype="int")

In [9]:
from PIL import Image
import os
import numpy as np
label=[]
data=[]

In [10]:
direc = ('dog/')

for i in os.listdir(direc):
    path = os.path.join(direc, i)
    img = Image.open(path)
    img = np.array(img)
    image = cv2.imread(path)
#     print(np.array(img))

In [11]:
# img.shape

In [12]:
image.shape

(180, 240, 3)

In [13]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [14]:
kernelBank = ( ("small_blur", smallBlur), ("large_blur", largeBlur), ("sharpen", sharpen), ("laplacian", laplacian), ("sobel_x", sobelX), ("sobel_y", sobelY), ("emboss", emboss))

In [15]:
for (kernelName, K) in kernelBank:
    
    print("[INFO] applying {} kernel".format(kernelName))
    convolveOutput = convolve(gray, K)
    opencvOutput = cv2.filter2D(gray, -1, K)
    
    cv2.imshow("Original", gray)
    
    cv2.imshow("{} - convole".format(kernelName), convolveOutput)
    cv2.imshow("{} - opencv".format(kernelName), opencvOutput)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

[INFO] applying small_blur kernel
[[ 95.44897959  95.44897959  94.65306122 ...  49.08163265  49.59183673
   50.46938776]
 [ 91.87755102  94.32653061  96.57142857 ...  46.06122449  46.04081633
   46.83673469]
 [ 87.40816327  92.02040816  96.93877551 ...  44.16326531  44.2244898
   44.81632653]
 ...
 [121.91836735 118.59183673 115.83673469 ... 119.44897959 119.30612245
  119.12244898]
 [109.10204082 108.51020408 108.10204082 ... 118.55102041 118.48979592
  118.40816327]
 [108.02040816 107.44897959 107.26530612 ... 117.73469388 117.85714286
  118.04081633]]
[[0.37430972 0.37430972 0.37118848 ... 0.19247699 0.19447779 0.19791917]
 [0.36030412 0.36990796 0.37871148 ... 0.18063225 0.18055222 0.18367347]
 [0.34277711 0.36086435 0.38015206 ... 0.17318928 0.17342937 0.1757503 ]
 ...
 [0.47811124 0.46506603 0.4542617  ... 0.46842737 0.46786715 0.46714686]
 [0.42785114 0.42553021 0.42392957 ... 0.46490596 0.46466587 0.46434574]
 [0.42360944 0.42136855 0.42064826 ... 0.46170468 0.46218487 0.462905

In [16]:
gray

array([[111,  86,  93, ...,  50,  37,  72],
       [121,  80,  68, ...,  58,  30,  35],
       [ 71,  37,  81, ...,  30,  49,  55],
       ...,
       [111, 111, 112, ..., 126, 118, 122],
       [109, 109, 110, ..., 125, 116, 115],
       [107, 107, 108, ..., 123, 116, 114]], dtype=uint8)